security:
  basic:
    enabled: true
  user:
    name: admin
    password: shiny
server:
    port: 8888
eureka:
    instance:
      hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  config: classpath:log4j2.xml