spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:\config\test.yml
  application:
    name: config-server
server:
  port: 6666
eureka:
  client:
    service-url:
      defaultZone: http://admin:shiny@localhost:8888/eureka/