eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:shiny@localhost:8888/eureka/
server:
  port: 8889
spring:
  application:
    name: consumer-ribbon
logging:
  config: classpath:log4j2.xml