-- MySQL Script generated by MySQL Workbench
-- Wed May  2 14:59:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ucenter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ucenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ucenter` DEFAULT CHARACTER SET utf8 ;
USE `ucenter` ;

-- -----------------------------------------------------
-- Table `ucenter`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`user` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`user` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `mobile` VARCHAR(45) NOT NULL,
  `password` (32) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `is_locked` TINYINT(1) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(36) NULL,
  `update_time` TIMESTAMP NULL,
  `update_by` VARCHAR(36) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ucenter`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`role` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`role` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `en_code` VARCHAR(20) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ucenter`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`permission` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`permission` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NULL,
  `type` TINYINT(1) NOT NULL,
  `permission_val` VARCHAR(45) NULL,
  `uri` VARCHAR(45) NULL,
  `icon` VARCHAR(20) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ucenter`.`user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`user_group` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`user_group` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `pid` VARCHAR(36) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ucenter`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`menu` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`menu` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `url` VARCHAR(50) NOT NULL,
  `pid` VARCHAR(36) NULL,
  `icon` VARCHAR(15) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ucenter`.`element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`element` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`element` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NULL,
  `code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ucenter`.`operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`operation` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`operation` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NULL,
  `code` VARCHAR(20) NOT NULL,
  `url_prefix` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ucenter`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`file` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`file` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `size` INT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` VARCHAR(36) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ucenter`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`user_role` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`user_role` (
  `user_id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`));


-- -----------------------------------------------------
-- Table `ucenter`.`user_group_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`user_group_role` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`user_group_role` (
  `group_id` VARCHAR(36) NOT NULL,
  `role_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`group_id`, `role_id`));


-- -----------------------------------------------------
-- Table `ucenter`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`role_permission` (
  `role_id` VARCHAR(36) NOT NULL,
  `permission_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`));


-- -----------------------------------------------------
-- Table `ucenter`.`permission_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`permission_menu` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`permission_menu` (
  `permission_id` VARCHAR(36) NOT NULL,
  `menu_id` VARCHAR(36) NULL,
  PRIMARY KEY (`permission_id`));


-- -----------------------------------------------------
-- Table `ucenter`.`permission_element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`permission_element` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`permission_element` (
  `permission_id` VARCHAR(36) NOT NULL,
  `element_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`permission_id`, `element_id`));


-- -----------------------------------------------------
-- Table `ucenter`.`permission_operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`permission_operation` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`permission_operation` (
  `permission_id` VARCHAR(36) NOT NULL,
  `operation_id` VARCHAR(36) NULL,
  PRIMARY KEY (`permission_id`));


-- -----------------------------------------------------
-- Table `ucenter`.`permission_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucenter`.`permission_file` ;

CREATE TABLE IF NOT EXISTS `ucenter`.`permission_file` (
  `permission_id` VARCHAR(36) NOT NULL,
  `file_id` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`permission_id`, `file_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
