server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.1.5.92:3306/ucenter?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: select 1
    filters: stat,wall
security:
  oauth2:
    resource:
      filter-order: 3