server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://10.1.5.92:3306/ucenter?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: select 1
    filters: stat,wall
  redis:
    host: 10.1.5.92
    port: 6379
    password: shiny
    luaSha: d6484e158be890dac21b51d3615fc0f9088e1683
  aop:
    proxy-target-class: true
    auto: true
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml